import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from './context/ThemeContext';
import { PostProvider } from "./context/PostContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <PostProvider>
        <ThemeProvider>{children}</ThemeProvider>  </PostProvider>
      </body>
    </html>
  );
}
